### ISSUE TITLE
vi ./Makefile

### ISSUE THREAD

**Issue by BuddhaDiedLaughing** [ulli-kroll/rtl8812bu#16]
vi ./Makefile
 "CONFIG_WIFI_MONITOR = n"  ==> "CONFIG_WIFI_MONITOR = y"
 "CONFIG_80211W = n"  ==>  "CONFIG_80211W = y"

_Originally posted by @liu-lulin in https://github.com/ulli-kroll/rtl8822bu/issues/4#issuecomment-484756117_

Hello & thank you for providing this.  I'm not sure I did this right but what I did seems to have resolved half my current issues.   

1. I found and edited the Makerfile in the Module folder.
2. I rebooted.

Thing is, at least when using Lazy Script, it's unable to start monitor mode.  Still says "wlan0mon: ERROR while getting interface flags; no such device."  What seems to be working, now, is the scan feature in Lazy Script which I'd also been struggling with, before.  Although, that could have resolved through one of a multitude of other things that I've tried.

Any advice?

Thank you!

**Comment by ulli-kroll** [comment]
Hi

Advice for this driver (and this code)
No, I'm sorry
Maybe I can easily add/check for missing code for rtl8822bu

My goal is something other, you will may find this somewhere in some other repository.
Maybe added with some random suffix, but be aware this *one* is currently not useful
