### ISSUE TITLE
EW-7822ULC_Linux_Wi-Fi_Driver_1.0.1.6

### ISSUE THREAD

**Issue by simonlui** [ulli-kroll/rtl8812bu#3]
Hello,

I would like to inform you that on Edimax's website, they have released a new version of their driver package from 2018-07-23. Whenever you have time, hopefully you should be able to find try and rebase your current driver code off that package. Not sure if it will help with the USB 3 modeswitch issues.

Details about the driver from the website:

1.0.1.6 | EW-7822ULC_Linux_Wi-Fi_Driver_1.0.1.6 Support Kernel : 2.6.24 ~ 4.15 | 2018-07-23

**Comment by ulli-kroll** [comment]
A quick response
Added new Edimax driver.
There is no code change in USB3 switch.
Thus current Realtek sources lacks (full) USB3 support.

Will push out ASAP
