### ISSUE TITLE
Does not build on Arch aarch64 (Rock 64 SBC)

### ISSUE THREAD

**Issue by f4exb** [ulli-kroll/rtl8812bu#5]
Hi,

the build does not work on my Rock 64 (https://www.pine64.org/?page_id=7147) running Arch Linux 64 bit (armv8):

```
make
make ARCH=aarch64 CROSS_COMPILE= -C /lib/modules/4.19.0-1-ARCH/build M=/opt/build/rtl8822bu  modules
make[1]: Entering directory '/usr/lib/modules/4.19.0-1-ARCH/build'
make[1]: *** No rule to make target 'modules'.  Stop.
make[1]: Leaving directory '/usr/lib/modules/4.19.0-1-ARCH/build'
make: *** [Makefile:512: modules] Error 2
```

**Comment by ulli-kroll** [comment]
Please read
https://github.com/aw/linux-build/blob/recipe-compile-kernel-module/recipes/kernel-module-compilation.md

I know this is hard on Popcorn Hour Transformer aka rock64
