### ISSUE TITLE
Make fails for Kernel 5.1

### ISSUE THREAD

**Issue by alitahir360** [ulli-kroll/rtl8812bu#9]
Nevermind, this issue can be closed/deleted

**Comment by alitahir360** [comment]
The `make` works fine for Kernel v5.0.11

**Comment by ulli-kroll** [comment]
FYI:
A patch for your previous issue (now deleted) issue, with filesystem functions is almost ready.
I removed all of this code.
Currently I'm in testing phase for this changes and I have a slightly annoying error in my buildroot config.
